"""Initial revision

Revision ID: d6a6a64ba93d
Revises: 
Create Date: 2025-03-20 08:35:32.399614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a6a64ba93d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Habit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Habit_id'), 'Habit', ['id'], unique=False)
    op.create_index(op.f('ix_Habit_name'), 'Habit', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Habit_name'), table_name='Habit')
    op.drop_index(op.f('ix_Habit_id'), table_name='Habit')
    op.drop_table('Habit')
    # ### end Alembic commands ###
